/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.unjfsc.quiz.java11.view;

/**
 *
 * @author TATIANA
 */
public class JPanelMostrarInformacion extends javax.swing.JPanel {

    /**
     * Creates new form JPanelMostrarInformacion
     */
    public JPanelMostrarInformacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtOrden = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(47, 147, 136));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 80));

        txtOrden.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtOrden.setForeground(new java.awt.Color(102, 102, 102));
        txtOrden.setBorder(null);
        jPanel1.add(txtOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 140, 30));

        jSeparator8.setBackground(new java.awt.Color(24, 46, 74));
        jSeparator8.setForeground(new java.awt.Color(24, 46, 74));
        jSeparator8.setAlignmentX(1.5F);
        jSeparator8.setAlignmentY(1.5F);
        jSeparator8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSeparator8.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 140, 10));

        jLabel19.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Orden:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, 40));

        txtNombre.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 140, 30));

        jSeparator9.setBackground(new java.awt.Color(24, 46, 74));
        jSeparator9.setForeground(new java.awt.Color(24, 46, 74));
        jSeparator9.setAlignmentX(1.5F);
        jSeparator9.setAlignmentY(1.5F);
        jSeparator9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSeparator9.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 140, 10));

        jLabel20.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Nombre:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, 40));

        txtApellido.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setBorder(null);
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 140, 30));

        jSeparator10.setBackground(new java.awt.Color(24, 46, 74));
        jSeparator10.setForeground(new java.awt.Color(24, 46, 74));
        jSeparator10.setAlignmentX(1.5F);
        jSeparator10.setAlignmentY(1.5F);
        jSeparator10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSeparator10.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 140, 10));

        jLabel21.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Apellido:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 90, 40));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 420, 170));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOrden;
    // End of variables declaration//GEN-END:variables
}
